### ISSUE TITLE
javax.el.ExpressionFactory -> Error

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud-samples/zuul-server#3]
Not sure if this is on my side or something to do with dependencies in the parent pom.  I did delete my .m2.  I have another hand written version based on the sample with the same error.  Using IntelliJ so could be something with IntelliJ.

This error happens on load.

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is javax.validation.ValidationException: Unable to instantiate Configuration`

`javax.validation.ValidationException: HV000183: Unable to load 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath`

**Comment by spencergibb** [comment]
You need `spring-boot-starter-web` as a dependency.

**Comment by ccit-spence** [comment]
That did fix it, then had another issue and had to add `spring-boot-starter-actuator`

Thanks for the quick response!
