### ISSUE TITLE
How to map a route

### ISSUE THREAD

**Issue by pchlebda** [spring-cloud-samples/zuul-server#8]
Hi,
I used that example and change an application.yml to the application.properties. Here it is:

````
zuul.routes.zuulserver.path=/self/**
zuul.routes.zuulserver.serviceId=zuulserver
zuulserver.ribbon.listOfServers=http://localhost:3030
zuulserver.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
eureka.client.enabled=false
logging.level.root=INFO
````
I would like to take advantage of ciruit breaker pattern and mapping.
When I added:
`zuul.routes.zuulserver.url=http://localhost:3030/some/path`
It works fine, but the documentation says `These simple url-routes don’t get executed as a HystrixCommand nor do they loadbalance multiple URLs with Ribbon`.

How can I map the path(**`/some/path`**) for my route?
`http://localhost:8080/self is mapped to http://localhost:3030/some/path`

I thought about:
`zuulserver.ribbon.listOfServers=http://localhost:3030/some/path` 
But it does not work since ribbon recognizes only host and port.

**Comment by ryanjbaxter** [comment]
Yes Hystrix only works with ribbon.  So if you want to use a URL you will ave to use `listOfServers`.  The path part comes from the path in the request made to zuul

**Comment by pchlebda** [comment]
How can I use circuit breaker with the path part ?

**Comment by ryanjbaxter** [comment]
Hystrix is automatically enabled when using Zuul + Ribbon nothing you ned to do

**Comment by pchlebda** [comment]
The problem is that I can't add path then. I would like

```http://localhost:8080/self is mapped to http://localhost:3030/some/path```

Is there any way of having it ?

**Comment by ryanjbaxter** [comment]
The path of the request made to the downstream service must come from the path of the request made to zuul.  Zuul is just acting as a proxy.  Unless you implement some kind of Zuul filter you cant transform the request.

**Comment by pchlebda** [comment]
Do you have any example of that?
I think it's a quite common scenario to have circuit breaker + path mapping in zuul.

**Comment by ryanjbaxter** [comment]
Here is a collection of zuul filters https://github.com/spring-cloud-samples/sample-zuul-filters

**Comment by pchlebda** [comment]
I've implemented my own filter that puts proper path mapping to context`requestURI`.
Are you going to implement such feature(circuit breaker + path mapping) in the future zuul version?

**Comment by ryanjbaxter** [comment]
We have no plans to support Hystrix wrapped URL path, right now you need to use Ribbon.  Can we close this issue?

**Comment by pchlebda** [comment]
Thanks.
Yes, you can close it.
